name: flutter_application_1 # Menambahkan nama proyek
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  url_launcher: ^6.2.6
  firebase_database: ^11.3.10
  geolocator: ^11.0.0
  http: ^1.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  speech_to_text: ^7.3.0
  flutter_blue_plus: ^1.31.14
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Paket untuk membuat ikon diletakkan di sini
  flutter_launcher_icons: ^0.13.1

# Konfigurasi untuk paket ikon diletakkan di sini
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
